const projects = [
  {
    id: 1,
    title: "COVID Tracker",
    category: "react",
    img: "./assets/react-covid-tracker.png",

    live_link: "https://covid-tracker-rt.netlify.app",
    repo_link: "https://github.com/rahul975337/Covid-tracker-react",
  },
  {
    id: 2,
    title: "Portfolio",
    category: "react",
    img: "./assets/portfolio-react.png",
    live_link: "https://rahul-tilwani.netlify.app/",
    repo_link: "https://github.com/rahul975337/React-Portfolio",
  },
  {
    id: 3,
    title: "Android apps",
    category: "android",
    img: "./assets/-covid-tracker.png",

    live_link: "https://covid-tracker-71c01.web.app/",
    repo_link: "https://github.com/rahul975337/Covid-tracker-react",
  },
  {
    id: 4,
    title: "flutter apps",
    category: "flutter",
    img: "./assets/-covid-tracker.png",

    live_link: "https://covid-tracker-71c01.web.app/",
    repo_link: "https://github.com/rahul975337/Covid-tracker-react",
  },
  {
    id: 5,
    title: "Theme Toggler",
    category: "react",
    img: "./assets/theme-toggler-react.png",
    live_link: "https://theme-toggler-rt.netlify.app/",
    repo_link:
      "https://github.com/rahul975337/REACT-HC-5-CONTEXT-API-THEME-TOGGLER",
  },
  {
    id: 6,
    title: "State Counter",
    category: "react",
    img: "./assets/state-counter.png",
    live_link: "https://state-counter-rt.netlify.app/",
    repo_link: "https://github.com/rahul975337/REACT-HC-3-STATE-COUNTER",
  },
  {
    id: 7,
    title: "Tic Tac Toe",
    category: "react",
    img: "./assets/tic-tac-toe.png",
    live_link: "https://tic-tac-toe-rt.netlify.app/",
    repo_link: "https://github.com/rahul975337/REACT-HC-4-TIC-TAC-TOE",
  },
  {
    id: 8,
    title: "Slider",
    category: "react",
    img: "./assets/slider.png",
    live_link: "https://slider-rt.netlify.app/",
    repo_link: "https://github.com/rahul975337/Slider",
  },
  {
    id: 9,
    title: "Menu",
    category: "react",
    img: "./assets/menu.png",
    live_link: "https://menu-rt.netlify.app",
    repo_link: "https://github.com/rahul975337/Menu",
  },
  {
    id: 10,
    title: "Accordion",
    category: "react",
    img: "./assets/accordion.png",
    live_link: "https://accordion-rt.netlify.app/",
    repo_link: "https://github.com/rahul975337/Accordion",
  },
  {
    id: 11,
    title: "Birthday Reminder",
    category: "react",
    img: "./assets/birthday-reminder.png",
    live_link: "https://birthday-reminder-rt.netlify.app/",
    repo_link: "https://github.com/rahul975337/Birthday-Reminder",
  },
  {
    id: 12,
    title: "Tabs",
    category: "react",
    img: "./assets/tabs.png",
    live_link: "https://tabs-rt.netlify.app/",
    repo_link: "https://github.com/rahul975337/Tabs",
  },
  {
    id: 13,
    title: "Reviews",
    category: "react",
    img: "./assets/reviews.png",
    live_link: "https://reviews-rt.netlify.app/",
    repo_link: "https://github.com/rahul975337/Reviews",
  },
  {
    id: 14,
    title: "Tours",
    category: "react",
    img: "./assets/tours.png",
    live_link: "https://tours-rt.netlify.app/",
    repo_link: "https://github.com/rahul975337/Tours",
  },
  {
    id: 15,
    title: "Arm Fitness",
    category: "web development",
    img: "./assets/arm-fitness.png",
    live_link: "https://arm-fitness-rt.netlify.app/",
    repo_link: "https://github.com/rahul975337/Gym-Website",
  },
  {
    id: 16,
    title: "Hover Board",
    category: "web development",
    img: "./assets/hover-board.png",
    live_link: "https://hover-board-rt.netlify.app/",
    repo_link: "https://github.com/rahul975337/hover-board",
  },
  {
    id: 17,
    title: "Codepen",
    category: "react",
    img: "./assets/codepen.png",
    live_link: "https://codepen-rt.netlify.app/",
    repo_link: "https://github.com/rahul975337/Codepen",
  },
  {
    id: 18,
    title: "Clock",
    category: "web development",
    img: "./assets/clock.png",
    live_link: "https://clock-rt.netlify.app/",
    repo_link: "https://github.com/rahul975337/Clock",
  },
  {
    id: 19,
    title: "Box Shadow Editor",
    category: "react",
    img: "./assets/box-shadow-editor.png",
    live_link: "https://boxshadow-editor-rt.netlify.app/",
    repo_link: "https://github.com/rahul975337/css-boxshadow-editor",
  },
  {
    id: 20,
    title: "React Todo",
    category: "react",
    img: "./assets/react-todo.png",
    live_link: "https://react-todo-context-api-rt.netlify.app/",
    repo_link: "https://github.com/rahul975337/REACT-HC-6-TODO-CONTEXT-API",
  },
  {
    id: 21,
    title: "Wave Animation",
    category: "web development",
    img: "./assets/wave-animation.png",
    live_link: "https://wave-animation-rt.netlify.app/",
    repo_link: "https://github.com/rahul975337/wave-animatioon",
  },
  {
    id: 22,
    title: "COLORRS",
    category: "web development",
    img: "./assets/colorrs.png",
    live_link: "https://colorrs-rt.netlify.app/",
    repo_link: "https://github.com/rahul975337/COLORRS-Website",
  },
  {
    id: 23,
    title: "Breaking bad",
    category: "react",
    img: "./assets/breaking-bad.png",
    live_link: "https://breaking-bad-rt.netlify.app/",
    repo_link: "https://github.com/rahul975337/Breaking-bad-api",
  },
  {
    id: 24,
    title: "Crypto",
    category: "react",
    img: "./assets/crypto.png",
    live_link: "https://crypto-rt.netlify.app/",
    repo_link:
      "https://github.com/rahul975337/Cryptocurrency-Finance-Price-Tracker-App",
  },
  {
    id: 25,
    title: "Reactbook",
    category: "react",
    img: "./assets/reactbook.png",
    live_link: "https://reactboook-rt.netlify.app/",
    repo_link: "https://github.com/rahul975337/Reactbook",
  },
  {
    id: 26,
    title: "Reactbnb",
    category: "react",
    img: "./assets/reactbnb.png",
    live_link: "https://reactbnb-rt.netlify.app/",
    repo_link: "https://github.com/rahul975337/Reactbnb",
  },
];
export default projects;
