const projects = [
  {
    id: 1,
    title: "COVID Tracker",
    category: "react",
    img: "./assets/react-covid-tracker.png",

    live_link: "https://covid-tracker-rt.netlify.app",
    repo_link: "https://github.com/rahul975337/Covid-tracker-react",
  },
  {
    id: 2,
    title: "Portfolio",
    category: "react",
    img: "./assets/portfolio-react.png",
    live_link: "https://rahul-tilwani.netlify.app/",
    repo_link: "https://github.com/rahul975337/React-Portfolio",
  },
  {
    id: 3,
    title: "COVID Tracker",
    category: "android",
    img: "./assets/-covid-tracker.png",

    live_link: "https://covid-tracker-71c01.web.app/",
    repo_link: "https://github.com/rahul975337/Covid-tracker-react",
  },
  {
    id: 4,
    title: "COVID Tracker",
    category: "flutter",
    img: "./assets/-covid-tracker.png",

    live_link: "https://covid-tracker-71c01.web.app/",
    repo_link: "https://github.com/rahul975337/Covid-tracker-react",
  },
  {
    id: 5,
    title: "Theme Toggler",
    category: "react",
    img: "./assets/theme-toggler-react.png",
    live_link: "https://theme-toggler-rt.netlify.app/",
    repo_link:
      "https://github.com/rahul975337/REACT-HC-5-CONTEXT-API-THEME-TOGGLER",
  },
  {
    id: 6,
    title: "State Counter",
    category: "react",
    img: "./assets/state-counter.png",
    live_link: "https://state-counter-rt.netlify.app/",
    repo_link: "https://github.com/rahul975337/REACT-HC-3-STATE-COUNTER",
  },
  {
    id: 7,
    title: "Tic Tac Toe",
    category: "react",
    img: "./assets/tic-tac-toe.png",
    live_link: "https://tic-tac-toe-rt.netlify.app/",
    repo_link: "https://github.com/rahul975337/REACT-HC-4-TIC-TAC-TOE",
  },
  {
    id: 8,
    title: "Slider",
    category: "react",
    img: "./assets/slider.png",
    live_link: "https://slider-rt.netlify.app/",
    repo_link: "https://github.com/rahul975337/Slider",
  },
  {
    id: 9,
    title: "Menu",
    category: "react",
    img: "./assets/menu.png",
    live_link: "https://menu-rt.netlify.app",
    repo_link: "https://github.com/rahul975337/Menu",
  },
  {
    id: 10,
    title: "Accordion",
    category: "react",
    img: "./assets/accordion.png",
    live_link: "https://accordion-rt.netlify.app/",
    repo_link: "https://github.com/rahul975337/Accordion",
  },
  {
    id: 11,
    title: "Birthday Reminder",
    category: "react",
    img: "./assets/birthday-reminder.png",
    live_link: "https://birthday-reminder-rt.netlify.app/",
    repo_link: "https://github.com/rahul975337/Birthday-Reminder",
  },
  {
    id: 12,
    title: "Tabs",
    category: "react",
    img: "./assets/tabs.png",
    live_link: "https://tabs-rt.netlify.app/",
    repo_link: "https://github.com/rahul975337/Tabs",
  },
  {
    id: 13,
    title: "Reviews",
    category: "react",
    img: "./assets/reviews.png",
    live_link: "https://reviews-rt.netlify.app/",
    repo_link: "https://github.com/rahul975337/Reviews",
  },
  {
    id: 14,
    title: "Tours",
    category: "react",
    img: "./assets/tours.png",
    live_link: "https://tours-rt.netlify.app/",
    repo_link: "https://github.com/rahul975337/Tours",
  },
   {
    id: 15,
    title: "Arm Fitness",
    category: "web development",
    img: "./assets/Screenshot (82).png",
    live_link: "https://arm-fitness-rt.netlify.app/",
    repo_link: "https://github.com/rahul975337/Gym-Website",
  },
];
export default projects;
